# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'verbose_name': 'discipline',
                'verbose_name_plural': 'disciplines',
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'verbose_name': 'medium',
                'verbose_name_plural': 'media',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('project_url', models.URLField(blank=True, verbose_name='project URL')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='completion date')),
                ('is_ongoing', models.BooleanField(verbose_name='is ongoing')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('description', models.TextField(verbose_name='description')),
                ('overview_image', models.ImageField(blank=True, upload_to=portfolio.models._get_upload_to_path, verbose_name='overview image')),
                ('detail_image', models.ImageField(blank=True, upload_to=portfolio.models._get_upload_to_path, verbose_name='detail image')),
                ('status', portfolio.models.StatusField(choices=[(1, 'drafted'), (2, 'published'), (3, 'removed')], db_index=True, default=1, verbose_name='status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.Client', verbose_name='client')),
                ('disciplines', models.ManyToManyField(related_name='projects', to='portfolio.Discipline', verbose_name='disciplines')),
                ('media', models.ManyToManyField(related_name='projects', to='portfolio.Medium', verbose_name='media')),
            ],
            options={
                'ordering': ('-completion_date', 'name'),
                'get_latest_by': 'completion_date',
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_projectpiece', to='contenttypes.ContentType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='portfolio.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witness', models.CharField(blank=True, max_length=255, verbose_name='witness')),
                ('witness_desc', models.CharField(blank=True, help_text='Describe their position or relationship.', max_length=255, verbose_name="witness' position")),
                ('date', models.DateField(verbose_name='date')),
                ('testimonial', models.TextField(verbose_name='testimonial')),
                ('status', portfolio.models.StatusField(choices=[(1, 'drafted'), (2, 'published'), (3, 'removed')], db_index=True, default=1, verbose_name='status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='portfolio.Client', verbose_name='client')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
            },
        ),
    ]
