# Generated by Django 2.2.28 on 2025-01-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectpiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='projectpiece',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_projectpiece', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='projectpiece',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='portfolio.Project'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='portfolio.Client', verbose_name='client'),
        ),
    ]
